/** Engine-transmission profiles (v3cars / OEM specs, May 2026 India). */
export type PowertrainKey = string;

export type PowertrainProfile = {
  engine: string;
  transmission: string;
  fuelType: string;
  power: string;
  torque: string;
  mileage: string;
};

export const powertrains: Record<string, PowertrainProfile> = {
  // Kia Seltos
  "seltos-petrol-mt": {
    engine: "1.5L Smartstream GDI",
    transmission: "6-speed Manual",
    fuelType: "Petrol",
    power: "115 PS",
    torque: "144 Nm",
    mileage: "17.0 kmpl",
  },
  "seltos-petrol-cvt": {
    engine: "1.5L Smartstream GDI",
    transmission: "CVT",
    fuelType: "Petrol",
    power: "115 PS",
    torque: "144 Nm",
    mileage: "17.7 kmpl",
  },
  "seltos-turbo-imt": {
    engine: "1.5L Turbo GDI",
    transmission: "6-speed iMT",
    fuelType: "Petrol",
    power: "160 PS",
    torque: "253 Nm",
    mileage: "17.7 kmpl",
  },
  "seltos-turbo-dct": {
    engine: "1.5L Turbo GDI",
    transmission: "7-speed DCT",
    fuelType: "Petrol",
    power: "160 PS",
    torque: "253 Nm",
    mileage: "17.9 kmpl",
  },
  "seltos-diesel-mt": {
    engine: "1.5L VGT Diesel",
    transmission: "6-speed Manual",
    fuelType: "Diesel",
    power: "116 PS",
    torque: "250 Nm",
    mileage: "20.7 kmpl",
  },
  "seltos-diesel-at": {
    engine: "1.5L VGT Diesel",
    transmission: "6-speed Automatic",
    fuelType: "Diesel",
    power: "116 PS",
    torque: "250 Nm",
    mileage: "19.1 kmpl",
  },
  // Hyundai Creta
  "creta-petrol-mt": {
    engine: "1.5L MPi Petrol",
    transmission: "6-speed Manual",
    fuelType: "Petrol",
    power: "115 PS",
    torque: "144 Nm",
    mileage: "17.4 kmpl",
  },
  "creta-petrol-at": {
    engine: "1.5L MPi Petrol",
    transmission: "IVT Automatic",
    fuelType: "Petrol",
    power: "115 PS",
    torque: "144 Nm",
    mileage: "16.8 kmpl",
  },
  "creta-diesel-mt": {
    engine: "1.5L U2 CRDi Diesel",
    transmission: "6-speed Manual",
    fuelType: "Diesel",
    power: "116 PS",
    torque: "250 Nm",
    mileage: "21.4 kmpl",
  },
  "creta-diesel-at": {
    engine: "1.5L U2 CRDi Diesel",
    transmission: "6-speed Automatic",
    fuelType: "Diesel",
    power: "116 PS",
    torque: "250 Nm",
    mileage: "18.4 kmpl",
  },
  "creta-turbo-at": {
    engine: "1.5L Turbo GDi Petrol",
    transmission: "7DCT",
    fuelType: "Petrol",
    power: "160 PS",
    torque: "253 Nm",
    mileage: "18.5 kmpl",
  },
  // Tata Nexon
  "nexon-petrol-6mt": {
    engine: "1.2L Revotron Turbo",
    transmission: "6-speed Manual",
    fuelType: "Petrol",
    power: "120 PS",
    torque: "170 Nm",
    mileage: "17.4 kmpl",
  },
  "nexon-petrol-5mt": {
    engine: "1.2L Revotron Turbo",
    transmission: "5-speed Manual",
    fuelType: "Petrol",
    power: "120 PS",
    torque: "170 Nm",
    mileage: "17.4 kmpl",
  },
  "nexon-petrol-amt": {
    engine: "1.2L Revotron Turbo",
    transmission: "6-speed AMT",
    fuelType: "Petrol",
    power: "120 PS",
    torque: "170 Nm",
    mileage: "17.1 kmpl",
  },
  "nexon-petrol-dct": {
    engine: "1.2L Revotron Turbo",
    transmission: "7-speed DCT",
    fuelType: "Petrol",
    power: "120 PS",
    torque: "170 Nm",
    mileage: "17.1 kmpl",
  },
  "nexon-diesel-mt": {
    engine: "1.5L Kryojet Turbo Diesel",
    transmission: "6-speed Manual",
    fuelType: "Diesel",
    power: "116 PS",
    torque: "260 Nm",
    mileage: "24.1 kmpl",
  },
  "nexon-diesel-dct": {
    engine: "1.5L Kryojet Turbo Diesel",
    transmission: "6-speed DCT",
    fuelType: "Diesel",
    power: "116 PS",
    torque: "260 Nm",
    mileage: "21.1 kmpl",
  },
  "nexon-cng-mt": {
    engine: "1.2L iCNG",
    transmission: "6-speed Manual",
    fuelType: "CNG",
    power: "100 PS",
    torque: "170 Nm",
    mileage: "26.99 km/kg",
  },
  // Tata Punch
  "punch-petrol-mt": {
    engine: "1.2L Revotron",
    transmission: "5-speed Manual",
    fuelType: "Petrol",
    power: "88 PS",
    torque: "115 Nm",
    mileage: "20.09 kmpl",
  },
  "punch-petrol-amt": {
    engine: "1.2L Revotron",
    transmission: "5-speed AMT",
    fuelType: "Petrol",
    power: "88 PS",
    torque: "115 Nm",
    mileage: "18.8 kmpl",
  },
  "punch-cng-mt": {
    engine: "1.2L iCNG",
    transmission: "5-speed Manual",
    fuelType: "CNG",
    power: "73 PS",
    torque: "103 Nm",
    mileage: "26.99 km/kg",
  },
  "punch-cng-amt": {
    engine: "1.2L iCNG",
    transmission: "5-speed AMT",
    fuelType: "CNG",
    power: "73 PS",
    torque: "103 Nm",
    mileage: "26.99 km/kg",
  },
  "punch-turbo-mt": {
    engine: "1.2L iTurbo",
    transmission: "6-speed Manual",
    fuelType: "Petrol",
    power: "120 PS",
    torque: "170 Nm",
    mileage: "20.0 kmpl",
  },
  // Hyundai Venue
  "venue-petrol-mt": {
    engine: "1.2L Kappa Petrol",
    transmission: "5-speed Manual",
    fuelType: "Petrol",
    power: "83 PS",
    torque: "115 Nm",
    mileage: "18.05 kmpl",
  },
  "venue-turbo-mt": {
    engine: "1.0L Turbo GDi",
    transmission: "6-speed Manual",
    fuelType: "Petrol",
    power: "120 PS",
    torque: "172 Nm",
    mileage: "18.74 kmpl",
  },
  "venue-turbo-dct": {
    engine: "1.0L Turbo GDi",
    transmission: "7-speed DCT",
    fuelType: "Petrol",
    power: "120 PS",
    torque: "172 Nm",
    mileage: "20.0 kmpl",
  },
  "venue-diesel-mt": {
    engine: "1.5L U2 CRDi Diesel",
    transmission: "6-speed Manual",
    fuelType: "Diesel",
    power: "116 PS",
    torque: "250 Nm",
    mileage: "20.99 kmpl",
  },
  "venue-diesel-at": {
    engine: "1.5L U2 CRDi Diesel",
    transmission: "6-speed Automatic",
    fuelType: "Diesel",
    power: "116 PS",
    torque: "250 Nm",
    mileage: "17.9 kmpl",
  },
  // Skoda Kylaq
  "kylaq-turbo-mt": {
    engine: "1.0L TSI",
    transmission: "6-speed Manual",
    fuelType: "Petrol",
    power: "116 PS",
    torque: "178 Nm",
    mileage: "19.68 kmpl",
  },
  "kylaq-turbo-at": {
    engine: "1.0L TSI",
    transmission: "6-speed Automatic",
    fuelType: "Petrol",
    power: "116 PS",
    torque: "178 Nm",
    mileage: "19.05 kmpl",
  },
};
